package com.appchat.activities.signupServices;

public enum SignupErrors {
    OK,
    EMPTY_FIELD,
    USERNAME_NOT_VALID,
    USERNAME_EXISTS,
    PASSWORD_NOT_VALID,
    PASSWORDS_NOT_MATCH,
    CONFIRM_BEFORE_PASSWORD,
    DISPLAY_NAME_NOT_VALID,
    INVALID_PROFILE_PIC,
    ERROR_UPLOADING_PROFILE_PIC,
    PIC_WRONG_FORMAT
}
